// Copyright (c) 2018 Formula Slug. All Rights Reserved.

// Current chip
#define STM32F4

// STM32F3
#ifdef STM32F3
#define ARBITRARY_PORT_1 GPIOA
#define ARBITRARY_PIN_1 GPIOA_ARD_A1

#define RIGHT_THROTTLE_PORT GPIOA
#define RIGHT_THROTTLE_PIN GPIOA_ARD_A3

#define LEFT_THROTTLE_PORT GPIOA
#define LEFT_THROTTLE_PIN GPIOA_ARD_A0

#define ARBITRARY_PORT_2 GPIOA
#define ARBITRARY_PIN_2 GPIOA_ARD_D2

#define ARBITRARY_PORT_3 GPIOB
#define ARBITRARY_PIN_3 GPIOB_ARD_D3

#define STARTUP_SOUND_PORT GPIOB
#define STARTUP_SOUND_PIN GPIOB_ARD_D4

#define BRAKE_LIGHT_PORT GPIOB
#define BRAKE_LIGHT_PIN GPIOB_ARD_D5
#endif

// STM32F4
#ifdef STM32F4
#define ARBITRARY_PORT_1 GPIOA
#define ARBITRARY_PIN_1 GPIOA_PIN1

#define RIGHT_THROTTLE_PORT GPIOA
#define RIGHT_THROTTLE_PIN GPIOA_PIN2

#define LEFT_THROTTLE_PORT GPIOA
#define LEFT_THROTTLE_PIN GPIOA_PIN3

#define ARBITRARY_PORT_2 GPIOA
#define ARBITRARY_PIN_2 GPIOA_PIN8

#define ARBITRARY_PORT_3 GPIOA
#define ARBITRARY_PIN_3 GPIOA_PIN15

#define STARTUP_SOUND_PORT GPIOB
#define STARTUP_SOUND_PIN GPIOB_PIN0

#define BRAKE_LIGHT_PORT GPIOB
#define BRAKE_LIGHT_PIN GPIOB_PIN1
#endif
